# DL chollet 2017 book

## chapter 2


In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 0s 0us/step


In [3]:
train_images.shape


(60000, 28, 28)

In [0]:
len(train_labels)


In [4]:
train_labels


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [2]:
# for the test data
test_images.shape
len(test_labels)
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

### 2.2

In [0]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

### 2.3


In [0]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

### 2.4 Preparing the image data

In [0]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

### 2.5 Preparing the labels

In [0]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [9]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s 90us/step - loss: 0.2569 - acc: 0.9261
Epoch 2/5
60000/60000 [==============================] - 5s 79us/step - loss: 0.1030 - acc: 0.9693
Epoch 3/5
60000/60000 [==============================] - 5s 78us/step - loss: 0.0689 - acc: 0.9795
Epoch 4/5
60000/60000 [==============================] - 5s 80us/step - loss: 0.0497 - acc: 0.9853
Epoch 5/5
60000/60000 [==============================] - 5s 81us/step - loss: 0.0374 - acc: 0.9886


In [10]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 62us/step


In [11]:
print('test_acc:', test_acc)

test_acc: 0.9808


### 2.2 Data representations for neural networks

In [0]:
import numpy as np
#x = np.array(12)
#x = np.array([12, 3, 6, 14])
x = np.array([[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]])

In [19]:
x


array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [20]:
x.ndim

2


2D matrix: 
first axis are called the rows, entries from the second axis
are called the columns.